// Generated by CoffeeScript 1.3.3
(function() {
  var Dictionary;

  Dictionary = Em.Namespace.create();

  (typeof exports !== "undefined" && exports !== null ? exports : this).Dictionary = Dictionary;

  Dictionary.Model = Em.Object.extend(Em.Comparable, {
    name: null,
    description: null,
    version: null,
    compare: function(other) {
      return Em.compare(Em.get(this, 'name'), Em.get(other, 'name'));
    }
  });

  Dictionary.Model.findAll = function() {
    var models;
    models = Em.ArrayProxy.create();
    App.api.getModels(models, Alfresco.Dictionary.Model);
    return models;
  };

  Dictionary.Model.findByName = function(name) {
    var model;
    model = Em.ObjectProxy.create();
    App.api.getModel(name, model, Alfresco.Dictionary.Model);
    return model;
  };

  Dictionary.DataType = Em.Object.extend(Em.Comparable, {
    name: null,
    compare: function(other) {
      return Em.compare(this.get('name'), other.get('name'));
    }
  });

  Dictionary.DataType.findAll = function() {
    var dataTypes;
    dataTypes = Em.ArrayProxy.create();
    App.api.getDataTypes(dataTypes, Alfresco.DataType);
    return dataTypes;
  };

  Dictionary.Namespace = Em.Object.extend(Em.Comparable, {
    prefixes: null,
    uri: null,
    compare: function(other) {
      return Em.compare(this.get('uri'), other.get('uri'));
    }
  });

  Dictionary.Namespace.findAll = function() {
    var namespaces;
    namespaces = Em.ArrayProxy.create();
    App.api.getNamespaces(namespaces, Alfresco.Namespace);
    return namespaces;
  };

}).call(this);
