// Generated by CoffeeScript 1.3.3
(function() {
  var Bootstrap;

  Bootstrap = Em.Namespace.create();

  (typeof exports !== "undefined" && exports !== null ? exports : this).Bootstrap = Bootstrap;

  Bootstrap.Button = Em.View.extend({
    template: Em.Handlebars.compile('\
    <input\
      {{bindAttr type="view.type"}} \
      {{bindAttr value="view.value"}}\
      {{bindAttr class="view.classes"}} \
    />\
  '),
    type: 'button',
    value: null,
    kind: 'default',
    classes: (function() {
      return "btn btn-" + (this.get('kind'));
    }).property('kind')
  });

  Bootstrap.TabItem = Em.View.extend({
    tagName: 'li',
    classNameBindings: 'isActive:active',
    template: Em.Handlebars.compile('  \
    <a data-toggle="tab" href="#">{{view.label}}</a>\
  '),
    label: (function() {
      return this.get('content.label') || this.get('content.name') || this.get('content.title');
    }).property('content'),
    click: function() {
      this.set('parentView.selection', this.get('content'));
      return false;
    },
    isActive: (function() {
      return this.get('parentView.selection') === this.get('content');
    }).property('parentView.selection')
  });

  Bootstrap.Tabs = Em.CollectionView.extend({
    tagName: 'ul',
    classNames: ['nav', 'nav-tabs'],
    itemViewClass: Bootstrap.TabItem,
    selection: null
  });

}).call(this);
