// Generated by CoffeeScript 1.3.3
(function() {
  var App;

  App = (typeof exports !== "undefined" && exports !== null ? exports : this).App;

  App.ApplicationController = Em.Controller.extend();

  App.DashboardController = Em.Controller.extend({
    updateContent: function() {
      var info,
        _this = this;
      info = Management.Info.find();
      return info.done(function() {
        return _this.set('content', info);
      });
    },
    extensionBundles: (function() {
      return this._filterExtensions({
        isCoreBundle: false
      });
    }).property('content'),
    coreBundles: (function() {
      return this._filterExtensions({
        isCoreBundle: true
      });
    }).property('content'),
    _filterExtensions: function(options) {
      var extensions;
      extensions = this.get('content.extensions');
      if (extensions) {
        return this.get('content.extensions').filter(function(extension) {
          return extension.isCoreBundle === options.isCoreBundle;
        });
      } else {
        return [];
      }
    }
  });

  App.RepositoryController = Em.Controller.extend();

  App.DictionaryController = Em.Controller.extend({
    content: null,
    selection: null,
    init: function() {
      return this.set('content', [App.Dictionary.MODELS, App.Dictionary.NAMESPACES, App.Dictionary.DATA_TYPES]);
    },
    selectionDidChange: (function() {
      return App.router.send(this.get('selection.value'));
    }).observes('selection')
  });

  App.ModelIndexController = Em.ArrayController.extend({
    sortProperties: ['name']
  });

  App.ModelDetailController = Em.Controller.extend();

  App.ModelNavigationController = Em.Controller.extend({
    selection: null
  });

  App.ModelDefinitionController = Em.Controller.extend();

  App.ClassDefinitionController = Em.Controller.extend();

  App.ModelTypeController = Em.Controller.extend();

  App.ModelAspectController = Em.Controller.extend();

  App.DataTypesController = Em.ArrayController.extend({
    sortProperties: ['name']
  });

  App.NamespacesController = Em.ArrayController.extend({
    sortProperties: ['uri']
  });

}).call(this);
