// Generated by CoffeeScript 1.3.3
(function() {
  var Management;

  Management = Em.Namespace.create();

  (typeof exports !== "undefined" && exports !== null ? exports : this).Management = Management;

  Management.Info = Em.Object.extend({
    symbolicName: null,
    version: null
  });

  Management.Info.reopenClass({
    find: function() {
      var info, result;
      info = Em.ObjectProxy.create();
      result = $.Deferred();
      App.api.getManagementInfo().done(function(data) {
        info.set('content', Management.Info.create(data));
        return result.resolve(info);
      });
      return result.promise(info);
    }
  });

}).call(this);
