// Generated by CoffeeScript 1.3.3
(function() {
  var App;

  App = (typeof exports !== "undefined" && exports !== null ? exports : this).App;

  App.Option = Em.Object.extend({
    value: null,
    label: null
  });

  App.Dictionary = Em.Namespace.create;

  App.Dictionary.MODELS = App.Option.create({
    label: 'Models',
    value: 'showModels'
  });

  App.Dictionary.DATA_TYPES = App.Option.create({
    label: 'Data Types',
    value: 'showDataTypes'
  });

  App.Dictionary.NAMESPACES = App.Option.create({
    label: 'Namespaces',
    value: 'showNamespaces'
  });

}).call(this);
